# file: roles/zookeeper/tasks/main.yml

- name: Zookeeper | Make sure zookeeper is not running under supervisord
  supervisorctl: name=zookeeper state=stopped

- include: dependencies.yml
- include: user.yml
- include: install.yml
- include: configure.yml
- include: supervise_zookeeper.yml
