# file: roles/zeromq/tasks/main.yml

- name: Zeromq | Make sure the zeromq dependencies are installed
  apt: pkg=binutils-doc

- name: Zeromq | Download the zeromq source in /tmp if not yet present
  command: wget http://download.zeromq.org/zeromq-{{ zeromq_version }}.tar.gz chdir=/tmp creates=/tmp/zeromq-{{ zeromq_version }}.tar.gz

- name: Zeromq | Untar the zeromq source in /tmp
  command: tar -xvzf /tmp/zeromq-{{ zeromq_version }}.tar.gz chdir=/tmp creates=/tmp/zeromq-{{ zeromq_version }}

- name: Zeromq | configure and make the zeromq source
  shell: cd /tmp/zeromq-{{ zeromq_version }} && ./configure && make -j $machine_cpu_count creates=/tmp/zeromq-{{ zeromq_version }}/Makefile

- name: Zeromq | make install zeromq
  shell: cd /tmp/zeromq-{{ zeromq_version }} && sudo make install creates=/usr/local/lib/libzmq.so
