# file: roles/nginx/tasks/dependencies.yml

- name: Nginx | Make sure the nginx dependencies are installed
  apt: pkg=$item
  with_items:
    - git
    - libgoogle-perftools-dev
    - libpcre3
    - libpcre3-dev
    - openssl
    - zlib1g-dev
