# file: roles/nginx/tasks/package.yml

- name: Nginx | Add the nginx repo to the apt sources
  apt_repository: repo='deb http://nginx.org/packages/ubuntu'
  sudo: yes

- name: Nginx | Add the nginx apt key
  apt_key: url=http://nginx.org/keys/nginx_signing.key
  sudo: yes

- include: commons.yml

- name: Nginx | Make sure nginx is installed
  apt: pkg=nginx
  sudo: yes
  notify:
    - restart nginx
