# file: setups/cloudbox_2.yml

- name: Collecting facts
  hosts: all
  gather_facts: yes

- include: ../roles/security.yml
- include: ../roles/ssl.yml
- include: ../roles/monit.yml
- include: ../roles/python.yml
- include: ../roles/nginx.yml
- include: ../roles/mysql.yml
- include: ../roles/mail.yml
- include: ../roles/vpn.yml
- include: ../roles/znc.yml
- include: ../roles/firewall.yml
