# file: roles/mysql/defaults/main.yml

mysql_root_password: 'password'

mysql_max_allowed_packet: '128M'
mysql_character_set_server: 'utf8'
mysql_collation_server: 'utf8_general_ci'
mysql_innodb_file_per_table: 'innodb_file_per_table'
