---
- name: Getting uwsgi...
  get_url: dest=/tmp url={{ uwsgi_download_url }}/{{ uwsgi_version }}.tar.gz
  sudo: no

- name: Unpacking uwsgi...
  command: chdir=/tmp /bin/tar xvf {{ uwsgi_version }}.tar.gz creates=/tmp/uwsgi-{{ uwsgi_version }}
  sudo: no

- name: Pushing uwsgi build config...
  copy: src=uwsgibuild.ini dest=/tmp/uwsgi-{{ uwsgi_version }}/buildconf/uwsgibuild.ini
  sudo: no

- name: Pushing uwsgi embeded config...
  template: src=embededconfig.ini dest=/tmp/uwsgi-{{ uwsgi_version }}/embededconfig.ini
  sudo: no

- name: Building uwsgi...
  shell: chdir=/tmp/uwsgi-{{ uwsgi_version }} python2.7 uwsgiconfig.py --build uwsgibuild
  sudo: no
  environment:
      UWSGICONFIG_RUBYPATH: ruby1.9.1
      UWSGICONFIG_PHPLIBDIR: /usr/lib/php5

- name: Making sure uwsgi plugin directory exists...
  file: state=directory path={{ uwsgi_lib_dir }} mode=0755

- name: Installing uwsgi...
  command: chdir=/tmp/uwsgi-{{ uwsgi_version }} install -s -m 0755 uwsgi /usr/local/bin/uwsgi
  notify: restart the uwsgi emperor

- name: Installing uwsgi plugins...
  shell: chdir=/tmp/uwsgi-{{ uwsgi_version }} install -s -m 0755 *.so {{ uwsgi_lib_dir }}
  notify: restart the uwsgi emperor
