# file: roles/cassandra.yml

- hosts: cassandra
  name: cassandra
  tasks:
    - include: supervisor/tasks/install.yml
    - include: supervisor/tasks/enable.yml
    - include: supervisor/tasks/stop.yml
    - include: cassandra/tasks/dependencies.yml
    - include: cassandra/tasks/user.yml
    - include: cassandra/tasks/install.yml
    - include: cassandra/tasks/configure.yml
    - include: cassandra/tasks/supervise_cassandra.yml
    - include: supervisor/tasks/start.yml
  handlers:
    - include: supervisor/handlers/main.yml
