# file: roles/common.yml

- hosts: all
  name: Basic setup of a machine
  tasks:
    - include: common/tasks/hostname.yml
    - include: common/tasks/timezone.yml
    - include: common/tasks/directories.yml
    - include: common/tasks/apt.yml
    - include: common/tasks/essentials.yml
    - include: common/tasks/tools.yml
    - include: common/tasks/git.yml
    - include: common/tasks/vim.yml
    - include: common/tasks/cron.yml
    - include: common/tasks/logwatch.yml
    - include: common/tasks/tmpreaper.yml
    - include: common/tasks/ssh.yml
    - include: common/tasks/pdns.yml
  handlers:
    - include: common/handlers/timezone.yml
    - include: common/handlers/cron.yml
    - include: common/handlers/pdns.yml
    - include: common/handlers/ssh.yml
