# file: role/mysql.yml

- hosts: mysql
  name: mysql
  tasks:
    - include: mysql/tasks/install.yml
    - include: mysql/tasks/configure.yml
    - include: mysql/tasks/secure.yml
    - include: mysql/tasks/monit.yml
      when: monit_protection == true
  handlers:
    - include: mysql/handlers/main.yml
