# file: roles/security.yml

- hosts: all
  name: Security related packages setup
  tasks:
    - include: security/tasks/fail2ban.yml
    - include: security/tasks/rkhunter.yml
    - include: security/tasks/lynis.yml
  handlers:
    - include: security/handlers/fail2ban.yml
