# file: roles/storm.yml

- hosts: storm
  name: General storm requirements
  tasks:
    - include: supervisor/tasks/install.yml
    - include: supervisor/tasks/enable.yml
    - include: supervisor/tasks/stop.yml
    - include: storm/tasks/dependencies.yml
    - include: zeromq/tasks/install.yml
    - include: zeromq/tasks/jzmq.yml
    - include: storm/tasks/user.yml
    - include: storm/tasks/install.yml
    - include: storm/tasks/configure.yml
    - include: supervisor/tasks/start.yml
  handlers:
    - include: supervisor/handlers/main.yml

- hosts: storm-nimbus
  name: Storm nimbus daemon
  tasks:
    - include: storm/tasks/supervise_nimbus.yml
  handlers:
    - include: supervisor/handlers/main.yml

- hosts: storm-supervisor
  name: Storm supervisor daemon
  tasks:
    - include: storm/tasks/supervise_supervisor.yml
  handlers:
    - include: supervisor/handlers/main.yml

- hosts: storm-drpc
  name: Storm drpc daemon
  tasks:
    - include: storm/tasks/supervise_drpc.yml
  handlers:
    - include: supervisor/handlers/main.yml
