# file: roles/supervisor.yml

- hosts: all
  name: supervisor
  tasks:
    - include: supervisor/tasks/install.yml
    - include: supervisor/tasks/enable.yml
  handlers:
    - include: supervisor/handlers/main.yml
