# file: roles/znc.yml

- hosts: znc
  name: znc
  tasks:
    - include: znc/tasks/user.yml
    - include: ssl/tasks/znc.yml
    - include: znc/tasks/install.yml
    - include: znc/tasks/monit.yml
      when: monit_protection == true
  handlers:
    - include: znc/handlers/main.yml
