# file: roles/zookeeper.yml

- hosts: zookeeper
  name: zookeeper
  tasks:
    - include: supervisor/tasks/install.yml
    - include: supervisor/tasks/enable.yml
    - include: supervisor/tasks/stop.yml
    - include: zookeeper/tasks/dependencies.yml
    - include: zookeeper/tasks/user.yml
    - include: zookeeper/tasks/install.yml
    - include: zookeeper/tasks/configure.yml
    - include: zookeeper/tasks/supervise_zookeeper.yml
    - include: supervisor/tasks/start.yml
  handlers:
    - include: supervisor/handlers/main.yml
