# file: roles/ssh/defaults/main.yml

ssh_settings:
  Port: "22"
  Protocol: "2"
  UsePrivilegeSeparation: "yes"
  KeyRegenerationInterval: "3600"
  ServerKeyBits: "768"
  SyslogFacility: "AUTH"
  LogLevel: "INFO"
  LoginGraceTime: "120"
  PermitRootLogin: "no"
  StrictModes: "yes"
  RSAAuthentication: "yes"
  PubkeyAuthentication: "yes"
  IgnoreRhosts: "yes"
  RhostsRSAAuthentication: "no"
  HostbasedAuthentication: "no"
  PermitEmptyPasswords: "no"
  ChallengeResponseAuthentication: "no"
  PasswordAuthentication: "no"
  X11Forwarding: "yes"
  X11DisplayOffset: "10"
  PrintMotd: "no"
  PrintLastLog: "yes"
  TCPKeepAlive: "yes"
  AcceptEnv: "LANG LC_*"
  Subsystem: "sftp /usr/lib/openssh/sftp-server"
  UsePAM: "yes"
  UseDNS: "no"
  ClientAliveInterval: "1750"
  ClientAliveCountMax: "0"
