# file: roles/kafka/tasks/dependencies.yml

- name: Kafka | Make sure the kafka dependencies are installed
  apt: pkg=$item
  with_items:
    - git
    - libboost-all-dev
    - libboost-dev
    - pkg-config
