# file: roles/common/tasks/apt.yml

- name: Common | apt | Update the sources list (/etc/apt/sources.list)
  template: src=apt/sources.list.j2 dest=/etc/apt/sources.list owner=root group=root mode=0644

- name: Common | apt | Update the apt cache
  apt: update_cache=yes

- name: Common | apt | Upgrade the installed packages
  apt: upgrade=yes

- name: Common | apt | Make sure make is installed
  apt: pkg=make

- debug: msg="If on vagrant - reboot the machine; login; run `sudo /etc/init.d/vboxadd setup` to repare the vagrant specifics."
