# file: roles/commons/tasks/main.yml

- name: Common | Make sure some basic tools are installed
  apt: pkg=$item
  with_items:
    - command-not-found
    - curl
    - debconf
    - dmidecode
    - htop
    - iftop
    - iotop
    - nmap
    - mosh
    - pciutils
    - sysstat
    - tmux
    - tshark

- name: Common | Make sure git is installed
  apt: pkg=git

- name: Common | Make sure encfs and dependencies are installed
  apt: pkg=$item
  with_items:
    - encfs
    - libfuse-dev
    - fuse-utils
