# file: roles/common/tasks/pdns.yml

- name: Common | pdns | Make sure powerdns/pdns-recursor is installed
  apt: pkg=pdns-recursor

- name: Common | pdns | Make sure pdns-recursor is enabled
  action: service name=pdns-recursor enabled=yes

- name: Common | pdns | Update the pdns-recursor configuration (/etc/powerdns/recursor.conf)
  template: src=pdns/recursor.conf.j2 dest=/etc/powerdns/recursor.conf owner=root group=root mode=0644
  notify:
    - restart pdns
