# file: roles/common/tasks/tmpreaper.yml

- name: Common | tmpreaper | Make sure tmpreaper is installed
  apt: pkg=tmpreaper

- name: Common | tmpreaper | Update the tmpreaper configuration (/etc/tmpreaper.conf)
  template: src=tmpreaper/tmpreaper.conf.j2 dest=/etc/tmpreaper.conf owner=root group=root mode=0644

- name: Common | tmpreaper | Set the tmpreaper cron
  cron: name=tmpreaper hour=$tmpreaper_cron_hour minute=$tmpreaper_cron_minute job=/usr/sbin/tmpreaper
  notify:
    - restart cron
